import { Head, router } from '@inertiajs/react'; import { Button } from '@/components/ui/button'; import { useState } from 'react';
export default function Index({ topics, chapters, filters }: any) {
    const [chapterId, setChapterId] = useState(filters.chapter_id || '');
    return (<><Head title="Topics" /><div className="flex h-full flex-1 flex-col gap-4 p-6">
        <div className="flex items-center justify-between"><h1 className="text-2xl font-bold">Topics</h1><Button onClick={() => router.visit(`/tenant/topics/create${chapterId?`?chapter_id=${chapterId}`:''}`)}>New Topic</Button></div>
        <form onSubmit={e => { e.preventDefault(); router.get('/tenant/topics', { chapter_id: chapterId }, { preserveState: true }); }} className="flex items-center gap-2">
            <select value={chapterId} onChange={e => setChapterId(e.target.value)} className="flex h-10 w-[350px] rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">All Chapters</option>{chapters.map((ch:any)=><option key={ch.id} value={ch.id}>{ch.chapter_title} ({ch.course?.name})</option>)}</select>
            <Button type="submit" variant="secondary">Filter</Button></form>
        <div className="rounded-md border bg-card"><table className="w-full text-sm"><thead><tr className="border-b"><th className="h-12 px-4 text-left font-medium">Order</th><th className="h-12 px-4 text-left font-medium">Title</th><th className="h-12 px-4 text-left font-medium">Chapter</th><th className="h-12 px-4 text-left font-medium">Video</th><th className="h-12 px-4 text-right font-medium">Actions</th></tr></thead>
        <tbody>{topics.data.map((t:any) => (<tr key={t.id} className="border-b"><td className="p-4 font-mono text-muted-foreground">{t.order_index}</td><td className="p-4 font-medium">{t.topic_title}</td><td className="p-4"><div className="text-sm">{t.chapter?.chapter_title}</div><div className="text-xs text-muted-foreground">{t.chapter?.course?.name}</div></td><td className="p-4">{t.video_url ? <a href={t.video_url} target="_blank" rel="noopener noreferrer" className="text-blue-600 underline text-xs">View</a> : <span className="text-muted-foreground text-xs">—</span>}</td><td className="p-4 text-right flex gap-2 justify-end"><Button variant="outline" size="sm" onClick={() => router.visit(`/tenant/topics/${t.id}/edit`)}>Edit</Button><Button variant="destructive" size="sm" onClick={() => { if(confirm('Delete?')) router.delete(`/tenant/topics/${t.id}`); }}>Delete</Button></td></tr>))}
        {topics.data.length===0 && <tr><td colSpan={5} className="p-4 text-center text-muted-foreground">No topics.</td></tr>}</tbody></table></div>
        <div className="flex justify-end gap-2">{topics.links.map((l:any,k:number) => <Button key={k} variant={l.active?"default":"outline"} disabled={!l.url} dangerouslySetInnerHTML={{__html:l.label}} onClick={() => l.url && router.visit(l.url)} size="sm" />)}</div>
    </div></>);
}
